2024-08-07 14:28:54,006 ERROR: Exception on /login [GET] [in /home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/fabi/microblog/app/routes.py", line 62, in login
    return render_template('login.html', title='Sing In', form=form)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/fabi/microblog/app/templates/login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "/home/fabi/microblog/app/templates/base.html", line 20, in top-level template code
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
2024-08-07 14:31:44,411 INFO: Microblog startup [in /home/fabi/microblog/app/__init__.py:49]
2024-08-07 14:31:45,843 ERROR: Exception on /login [GET] [in /home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/fabi/microblog/app/routes.py", line 62, in login
    return render_template('login.html', title='Sing In', form=form)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/fabi/microblog/app/templates/login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "/home/fabi/microblog/app/templates/base.html", line 20, in top-level template code
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
2024-08-07 14:40:39,131 INFO: Microblog startup [in /home/fabi/microblog/app/__init__.py:49]
2024-08-07 14:40:41,389 ERROR: Exception on /login [GET] [in /home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/fabi/microblog/app/routes.py", line 62, in login
    return render_template('login.html', title='Sing In', form=form)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/fabi/microblog/app/templates/login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "/home/fabi/microblog/app/templates/base.html", line 27, in top-level template code
    <a class="nav-link" aria-current="page" href="{{ url_for('main.index') }}">{{ _('Home') }}</a>
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
2024-08-07 14:41:16,536 INFO: Microblog startup [in /home/fabi/microblog/app/__init__.py:49]
2024-08-07 14:41:18,198 ERROR: Exception on /login [GET] [in /home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/fabi/microblog/app/routes.py", line 62, in login
    return render_template('login.html', title='Sing In', form=form)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/fabi/microblog/app/templates/login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "/home/fabi/microblog/app/templates/base.html", line 27, in top-level template code
    <a class="nav-link" aria-current="page" href="{{ url_for('index') }}">{{ _('Home') }}</a>
  File "/home/fabi/microblog/venv/lib/python3.10/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: '_' is undefined
2024-08-07 14:48:09,999 INFO: Microblog startup [in /home/fabi/microblog/app/__init__.py:49]
